/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author Steffie
 */
public class DetailsDialogue extends javax.swing.JDialog {

    /**
     * Creates new form DetailsDialogue
     */
    
     
    public DetailsDialogue(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(MainWindow.backgroundColorPanel);
        btNextSide.setBackground(MainWindow.backgroundColorButton);
        btPreviousSide.setBackground(MainWindow.backgroundColorButton);
        this.setResizable(false);
        setLocationRelativeTo(parent);
        this.setIconImage(new ImageIcon(getClass().getResource("jhlogo.jpg")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBottomBar = new javax.swing.JPanel();
        lbDate = new javax.swing.JLabel();
        btPreviousSide = new javax.swing.JButton();
        btNextSide = new javax.swing.JButton();
        pnContainer = new javax.swing.JPanel();
        pnCompany = new javax.swing.JPanel();
        spDetailsCompany = new javax.swing.JScrollPane();
        tbDetailsCompany = new javax.swing.JTable();
        pnCompanyText = new javax.swing.JPanel();
        lbCompanyName = new javax.swing.JLabel();
        lbCompanyTableName = new javax.swing.JLabel();
        pnCustomer = new javax.swing.JPanel();
        spDetailsCustomer = new javax.swing.JScrollPane();
        tbDetailsCustomer = new javax.swing.JTable();
        pnCustomerText = new javax.swing.JPanel();
        lbCustomerName = new javax.swing.JLabel();
        lbCustomerTableName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnBottomBar.setBackground(new java.awt.Color(229, 229, 229));
        pnBottomBar.setLayout(new java.awt.BorderLayout());

        lbDate.setBackground(new java.awt.Color(229, 229, 229));
        lbDate.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDate.setText("08.07.2015");
        lbDate.setOpaque(true);
        pnBottomBar.add(lbDate, java.awt.BorderLayout.CENTER);

        btPreviousSide.setBackground(new java.awt.Color(229, 229, 229));
        btPreviousSide.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btPreviousSide.setText("<");
        btPreviousSide.setMaximumSize(new java.awt.Dimension(50, 35));
        btPreviousSide.setMinimumSize(new java.awt.Dimension(50, 35));
        btPreviousSide.setPreferredSize(new java.awt.Dimension(50, 35));
        btPreviousSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPreviousSide(evt);
            }
        });
        pnBottomBar.add(btPreviousSide, java.awt.BorderLayout.WEST);

        btNextSide.setBackground(new java.awt.Color(229, 229, 229));
        btNextSide.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btNextSide.setText(">");
        btNextSide.setMaximumSize(new java.awt.Dimension(50, 35));
        btNextSide.setMinimumSize(new java.awt.Dimension(50, 35));
        btNextSide.setPreferredSize(new java.awt.Dimension(50, 35));
        btNextSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNextSide(evt);
            }
        });
        pnBottomBar.add(btNextSide, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnBottomBar, java.awt.BorderLayout.SOUTH);

        pnContainer.setBackground(new java.awt.Color(229, 229, 229));
        pnContainer.setLayout(new java.awt.GridLayout(1, 2));

        pnCompany.setBackground(new java.awt.Color(229, 229, 229));
        pnCompany.setLayout(new java.awt.BorderLayout());

        spDetailsCompany.setBackground(new java.awt.Color(229, 229, 229));

        tbDetailsCompany.setBackground(new java.awt.Color(229, 229, 229));
        tbDetailsCompany.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbDetailsCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "xy", "25"},
                {"2", "me", "87"},
                {"23", "njnj", null}
            },
            new String [] {
                "Column 1", "Column 2", "Column 3"
            }
        ));
        spDetailsCompany.setViewportView(tbDetailsCompany);

        pnCompany.add(spDetailsCompany, java.awt.BorderLayout.CENTER);

        pnCompanyText.setBackground(new java.awt.Color(229, 229, 229));
        pnCompanyText.setLayout(new java.awt.GridLayout(2, 1));

        lbCompanyName.setBackground(new java.awt.Color(229, 229, 229));
        lbCompanyName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbCompanyName.setText("Principal");
        lbCompanyName.setOpaque(true);
        pnCompanyText.add(lbCompanyName);

        lbCompanyTableName.setBackground(new java.awt.Color(229, 229, 229));
        lbCompanyTableName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCompanyTableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCompanyTableName.setText("Table Name");
        lbCompanyTableName.setOpaque(true);
        pnCompanyText.add(lbCompanyTableName);

        pnCompany.add(pnCompanyText, java.awt.BorderLayout.PAGE_START);

        pnContainer.add(pnCompany);

        pnCustomer.setBackground(new java.awt.Color(229, 229, 229));
        pnCustomer.setLayout(new java.awt.BorderLayout());

        spDetailsCustomer.setBackground(new java.awt.Color(229, 229, 229));

        tbDetailsCustomer.setBackground(new java.awt.Color(229, 229, 229));
        tbDetailsCustomer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbDetailsCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "xy", "25"},
                {"2", "me", "87"}
            },
            new String [] {
                "Column 1", "Column 2", "Column 3"
            }
        ));
        spDetailsCustomer.setViewportView(tbDetailsCustomer);

        pnCustomer.add(spDetailsCustomer, java.awt.BorderLayout.CENTER);

        pnCustomerText.setBackground(new java.awt.Color(229, 229, 229));
        pnCustomerText.setLayout(new java.awt.GridLayout(2, 1));

        lbCustomerName.setBackground(new java.awt.Color(229, 229, 229));
        lbCustomerName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbCustomerName.setText("Customer");
        lbCustomerName.setOpaque(true);
        pnCustomerText.add(lbCustomerName);

        lbCustomerTableName.setBackground(new java.awt.Color(229, 229, 229));
        lbCustomerTableName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustomerTableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomerTableName.setText("Table Name");
        lbCustomerTableName.setOpaque(true);
        pnCustomerText.add(lbCustomerTableName);

        pnCustomer.add(pnCustomerText, java.awt.BorderLayout.PAGE_START);

        pnContainer.add(pnCustomer);

        getContentPane().add(pnContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onPreviousSide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPreviousSide
        // TODO add your handling code here:
    }//GEN-LAST:event_onPreviousSide

    private void onNextSide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNextSide
        // TODO add your handling code here:
    }//GEN-LAST:event_onNextSide

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailsDialogue dialog = new DetailsDialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNextSide;
    private javax.swing.JButton btPreviousSide;
    private javax.swing.JLabel lbCompanyName;
    private javax.swing.JLabel lbCompanyTableName;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbCustomerTableName;
    private javax.swing.JLabel lbDate;
    private javax.swing.JPanel pnBottomBar;
    private javax.swing.JPanel pnCompany;
    private javax.swing.JPanel pnCompanyText;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnCustomer;
    private javax.swing.JPanel pnCustomerText;
    private javax.swing.JScrollPane spDetailsCompany;
    private javax.swing.JScrollPane spDetailsCustomer;
    private javax.swing.JTable tbDetailsCompany;
    private javax.swing.JTable tbDetailsCustomer;
    // End of variables declaration//GEN-END:variables
}
