/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author Sarah
 */
public class TableDialogue extends javax.swing.JDialog 
{
    /**
     * Creates new form TableDialogue
     */
    private boolean ok = false;
    
    public TableDialogue(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(MainWindow.backgroundColorPanel);
        btCancel.setBackground(MainWindow.backgroundColorButton);
        btOk.setBackground(MainWindow.backgroundColorButton);
        this.setLocationRelativeTo(parent);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTables = new javax.swing.JLabel();
        pnTableButton = new javax.swing.JPanel();
        pnButtons = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        spTables = new javax.swing.JScrollPane();
        liTables = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        lbTables.setBackground(new java.awt.Color(229, 229, 229));
        lbTables.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbTables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTables.setText("Tables");
        lbTables.setToolTipText("");
        lbTables.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbTables.setMaximumSize(new java.awt.Dimension(55, 35));
        lbTables.setMinimumSize(new java.awt.Dimension(55, 35));
        lbTables.setOpaque(true);
        lbTables.setPreferredSize(new java.awt.Dimension(55, 35));
        getContentPane().add(lbTables, java.awt.BorderLayout.PAGE_START);

        pnTableButton.setBackground(new java.awt.Color(229, 229, 229));
        pnTableButton.setLayout(new java.awt.BorderLayout(10, 10));

        pnButtons.setBackground(new java.awt.Color(229, 229, 229));
        pnButtons.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        btOk.setBackground(new java.awt.Color(229, 229, 229));
        btOk.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btOk.setText("OK");
        btOk.setMaximumSize(new java.awt.Dimension(50, 70));
        btOk.setMinimumSize(new java.awt.Dimension(50, 70));
        btOk.setPreferredSize(new java.awt.Dimension(50, 70));
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOK(evt);
            }
        });
        pnButtons.add(btOk);

        btCancel.setBackground(new java.awt.Color(229, 229, 229));
        btCancel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btCancel.setText("Cancel");
        btCancel.setMaximumSize(new java.awt.Dimension(50, 70));
        btCancel.setMinimumSize(new java.awt.Dimension(50, 70));
        btCancel.setPreferredSize(new java.awt.Dimension(50, 70));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        pnButtons.add(btCancel);

        pnTableButton.add(pnButtons, java.awt.BorderLayout.PAGE_END);

        spTables.setBackground(new java.awt.Color(229, 229, 229));

        liTables.setBackground(new java.awt.Color(229, 229, 229));
        liTables.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        spTables.setViewportView(liTables);

        pnTableButton.add(spTables, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnTableButton, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOK
        ok = true;
        dispose();
        DownloadDialogue downloadDialogue = new DownloadDialogue(null, true);
        downloadDialogue.setVisible(true);
    }//GEN-LAST:event_onOK

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    public boolean getOK() 
    {
        return ok;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableDialogue dialog = new TableDialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbTables;
    private javax.swing.JList liTables;
    private javax.swing.JPanel pnButtons;
    private javax.swing.JPanel pnTableButton;
    private javax.swing.JScrollPane spTables;
    // End of variables declaration//GEN-END:variables
}
